const tiers = [
  [160,"Krakatice metakognitivní","Ví, co ví, ví, co neví, a dokonce pozná rozdíl. Internet ji odmítá, protože takový obsah nelze nacpat do patnáctisekundového tanečku."],
  [150,"Sova pochybující","Než něco veřejně prohlásí, položí si otázku, zda tomu opravdu rozumí. Kvůli této prodlevě nikdy nenatočí deset videí denně."],
  [140,"Delfín sebereflexivní","Dokáže komunikovat, spolupracovat a pochopit, že kritika nemusí být útok. Na sociálních sítích je proto veden jako ohrožený druh."],
  [130,"Chobotnice strategická","Zvládne několik činností současně, rozezná reklamu od doporučení a chápe, že „spolupráce“ není přírodní jev."],
  [120,"Vrána ověřovací","Používá nástroje, pamatuje si příčiny a následky a před sdílením občas otevře i zdroj. Tím začíná být pro algoritmus podezřelá."],
  [110,"Influencer souvislý","Dokáže pronést dvě souvislé věty na jeden nádech. Věty už mají podmět a přísudek, pouze spolu zatím významově nespolupracují."],
  [100,"Člověk standardní","Umí přečíst návod, porovnat dvě informace a připustit možnost omylu. Poslední schopnost na internetu běžně deaktivuje."],
  [90,"Papoušek motivační","Umí zopakovat několik cizích mouder. Pořadí slov se občas změní a vznikne věta, podle které je chudoba otázkou špatných vibrací."],
  [80,"Straka nákupní","Dokáže rozlišit třpytky, kamínky a plastové zlato na vzdálenost padesáti metrů. Cenovku objeví až bankovní aplikace."],
  [70,"Mistr uhelné gastronomie","Dokáže připravit jídlo podle receptu. Pokrm obvykle spálí, ale správným filtrem z něj vytvoří „rustikální domácí variantu“."],
  [60,"Křeček produktivní","Celý den běhá, natáčí, stříhá a plánuje. Večer zjistí, že vytvořil čtyři minuty obsahu o tom, že dnes nestíhal."],
  [50,"Holub diskusní","Vstoupí do debaty, shodí figurky, zanechá po sobě nepořádek a odejde s pocitem vítězství."],
  [40,"Zlatá rybka omluvná","Každé tři týdny natočí stejné vysvětlení a pokaždé je přesvědčena, že se situace stala poprvé."],
  [30,"Slimák lesklý","Sleduje třpytivou stopu a nakupuje všechno, co se leskne. Funkci předmětu zkoumá až po rozbalovacím videu."],
  [20,"Medúza trendová","Nemá centralizovaný mozek, ale bezpečně pozná, kterým směrem právě pluje dav."],
  [10,"Pokojová rostlina","Otáčí se za světlem. Internetový poddruh výhradně za kruhovým světlem a sponzorskou smlouvou."],
  [0,"Kámen základní","Nemá nervovou soustavu. Přesto dokáže být argumentačně pevnější než některá reakční videa."]
];
const people = [
  ["adela","Adéla Pulcová","Shopaholicadel"],["terka","Tereza Šulganová","Život Terky"],["kaluba","Matouš Kaluba",""],["gangstaboy","Tadeáš Veselý","Gangstaboy"],["lauberova","Nikola Lauberová",""],["bejr","Aleš Bejr","Psychopat"],["samir","Samir Margina",""],["gelnarova","Hana Gelnarová",""],["laduska","Lada Kašparová Horová","Laduška"],["kubenka","Tadeáš Kuběnka",""],["sugar","Denisa Kouřilková","Sugar Denny"],["datel","Marek Valášek","Datel"],["kajumi","Adam Kajumi",""],["grznar","Filip Grznár",""],["mike","Mike Oganesjan","Detektiv Mike"],["tary","Taras Povoroznyk","Tary"],["freescoot","Jakub Smrek","Freescoot"],["speaker","Jakub Jíra","Speaker"],["alagia","Dominique Alagia",""],["kamen","Ondřej Untermüller","Kluk s kamením"],["polackova","Eva Poláčková",""],["jeptiska","Jeptiška naruby","TikTok"]
].map(([id,name,alias],i)=>({id,name,alias,color:`hsl(${(i*47)%360} 68% 48%)`,color2:`hsl(${(i*47+65)%360} 63% 28%)`}));
const defaultPhotos = new Set(["adela","terka","kaluba","gangstaboy","lauberova","bejr","samir","gelnarova","laduska","kubenka","sugar","datel","kajumi","grznar","mike","tary","freescoot","speaker","alagia","kamen","polackova"]);
const pngPhotos = new Set(["bejr","gangstaboy","samir"]);
const photoFor = id => state.photos[id] || (defaultPhotos.has(id) ? `assets/portraits/${id}.${pngPhotos.has(id)?"png":"jpg"}` : "");

const KEY="bizar-iq-tier-v1"; let state=JSON.parse(localStorage.getItem(KEY)||"null")||{placements:{},photos:{}}; let activeId=null;
const board=document.querySelector("#board"),pool=document.querySelector("#pool"),search=document.querySelector("#search");
const esc=s=>s.replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function initials(p){return p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}
function hue(iq){return `hsl(${Math.round(iq/160*285)} 96% 55%)`}
function buildBoard(){board.innerHTML=tiers.map(([iq,title,text])=>`<article class="tier"><div class="iq-cell" style="--tier:${hue(iq)}"><div class="iq-number"><small>IQ</small>${iq}</div></div><div class="desc" title="${esc(text)}"><h3>${title}</h3><p>${text}</p></div><div class="tier-zone dropzone" data-iq="${iq}"></div></article>`).join("")}
function card(p){const photo=photoFor(p.id);return `<div class="card" draggable="true" data-id="${p.id}" title="Přetáhni do zvoleného IQ"><div class="portrait" style="--c1:${p.color};--c2:${p.color2};${photo?`background-image:url('${photo}')`:""}"><span class="initials" ${photo?'style="display:none"':""}>${initials(p)}</span><button class="photo-btn" aria-label="Změnit fotografii" title="Změnit fotografii">✎</button></div><div class="card-name">${esc(p.alias||p.name)}</div></div>`}
function render(){document.querySelectorAll(".tier-zone").forEach(z=>z.innerHTML="");pool.innerHTML="";let visible=0;const q=search.value.trim().toLocaleLowerCase("cs");people.forEach(p=>{if(q&&!`${p.name} ${p.alias}`.toLocaleLowerCase("cs").includes(q))return;visible++;const target=state.placements[p.id];(target===undefined?pool:document.querySelector(`.tier-zone[data-iq="${target}"]`))?.insertAdjacentHTML("beforeend",card(p))});const unplaced=people.filter(p=>state.placements[p.id]===undefined).length;document.querySelector("#poolCount").textContent=`${unplaced} z ${people.length} neumístěno`;if(!pool.children.length)pool.innerHTML=`<span class="empty">${q?"Hledání nemá výsledek":"Všichni už dostali svůj verdikt."}</span>`;bindCards()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function toast(t){const el=document.querySelector("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1700)}
function bindCards(){document.querySelectorAll(".card").forEach(el=>{el.addEventListener("dragstart",e=>{activeId=el.dataset.id;el.classList.add("dragging");e.dataTransfer.effectAllowed="move"});el.addEventListener("dragend",()=>el.classList.remove("dragging"));el.querySelector(".photo-btn").addEventListener("click",e=>{e.stopPropagation();openPhoto(el.dataset.id)})})}
function bindZones(){document.querySelectorAll(".dropzone").forEach(z=>{z.addEventListener("dragover",e=>{e.preventDefault();z.classList.add("drag-over")});z.addEventListener("dragleave",()=>z.classList.remove("drag-over"));z.addEventListener("drop",e=>{e.preventDefault();z.classList.remove("drag-over");if(!activeId)return;if(z.dataset.iq==="pool")delete state.placements[activeId];else state.placements[activeId]=Number(z.dataset.iq);save();render()})})}
function openPhoto(id){activeId=id;const p=people.find(x=>x.id===id),photo=photoFor(id),av=document.querySelector("#dialogAvatar");document.querySelector("#dialogName").textContent=p.name+(p.alias?` alias ${p.alias}`:"");av.textContent=photo?"":initials(p);av.style.background=`${photo?`url('${photo}') center/cover,`:""}linear-gradient(135deg,${p.color},${p.color2})`;document.querySelector("#photoDialog").showModal()}
buildBoard();render();bindZones();search.addEventListener("input",render);
document.querySelector("#resetBtn").addEventListener("click",()=>{if(confirm("Vrátit všechny influencery zpět nahoru? Fotografie zůstanou uložené.")){state.placements={};save();render();toast("Tier list byl vyčištěn")}});
document.querySelector("#compactBtn").addEventListener("click",()=>{document.body.classList.toggle("stream");toast(document.body.classList.contains("stream")?"Režim streamu zapnut":"Ovládání zobrazeno")});
document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="s"&&!/input/i.test(e.target.tagName)){document.body.classList.toggle("stream")}});
document.querySelector("#photoInput").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;if(file.size>12_000_000){toast("Fotka je příliš velká (max. 12 MB)");return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=420,scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=size;canvas.height=size;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);state.photos[activeId]=canvas.toDataURL("image/jpeg",.78);save();document.querySelector("#photoDialog").close();render();toast("Fotografie oříznuta a uložena")};img.src=reader.result};reader.readAsDataURL(file);e.target.value=""});
document.querySelector("#removePhoto").addEventListener("click",()=>{delete state.photos[activeId];save();document.querySelector("#photoDialog").close();render();toast("Fotografie odstraněna")});
